# Generated by Django 5.2.8 on 2025-11-25 14:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Concessionnaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=64)),
                ('siret', models.CharField(max_length=14)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=512)),
                ('type', models.CharField(choices=[('moto', 'Moto'), ('auto', 'Auto')], max_length=4)),
                ('marque', models.CharField(max_length=64)),
                ('image', models.CharField(max_length=256)),
                ('chevaux', models.IntegerField()),
                ('prix_ht', models.DecimalField(decimal_places=2, max_digits=12)),
                ('contenu', models.TextField()),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_mise_a_jour', models.DateTimeField(auto_now=True)),
                ('auteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenu', models.TextField()),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_mise_a_jour', models.DateTimeField(auto_now=True)),
                ('auteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commentaires', to='ConcessionaireData.product')),
            ],
        ),
        migrations.CreateModel(
            name='Vehicule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('moto', 'Moto'), ('auto', 'Auto')], max_length=4)),
                ('marque', models.CharField(max_length=64)),
                ('image', models.CharField(max_length=256)),
                ('chevaux', models.IntegerField()),
                ('prix_ht', models.DecimalField(decimal_places=2, max_digits=12)),
                ('concessionnaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicules', to='ConcessionaireData.concessionnaire')),
            ],
        ),
    ]
