# Generated by Django 5.2.8 on 2025-11-27 13:43

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Concessionnaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=64)),
                ('siret', models.CharField(max_length=14, validators=[django.core.validators.RegexValidator(message='Le SIRET doit contenir exactement 14 chiffres.', regex='^\\d{14}$')])),
            ],
        ),
        migrations.CreateModel(
            name='Vehicule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('moto', 'Moto'), ('auto', 'Auto')], max_length=4)),
                ('marque', models.CharField(max_length=64)),
                ('image', models.CharField(max_length=256)),
                ('chevaux', models.IntegerField()),
                ('prix_ht', models.DecimalField(decimal_places=2, max_digits=12)),
                ('concessionnaire', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vehicules', to='ConcessionaireData.concessionnaire')),
            ],
        ),
    ]
