# Generated by Django 5.2.8 on 2025-11-25 15:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ConcessionaireData', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concessionnaire',
            name='siret',
            field=models.CharField(max_length=14, validators=[django.core.validators.RegexValidator(message='SIRET must be exactly 14 digits.', regex='^\\d{14}$')]),
        ),
    ]
