# Generated by Django 5.2.7 on 2025-11-26 14:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ConcessionaireData', '0002_alter_concessionnaire_siret'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concessionnaire',
            name='siret',
            field=models.CharField(max_length=14, validators=[django.core.validators.RegexValidator(message='Le SIRET doit contenir exactement 14 chiffres.', regex='^\\d{14}$')]),
        ),
    ]
